-- P1-SEC-01 support script. NOT a migration. LOCAL USE / EMERGENCY REFERENCE ONLY.
--
-- Recreates the exact ACL state production had BEFORE the privilege baseline hardening, from the
-- read-only production inventory taken 2026-09-21 (default ACLs of owner postgres in public, table /
-- column / sequence / function grants for anon, authenticated, service_role). Two uses:
--   1. Prove the hardening migration converges from PRODUCTION'S real starting point, not just from a
--      fresh local database:
--        docker exec -i supabase_db_ZenWard psql -U postgres -d postgres -f - < supabase/tests/support/emulate_production_acl_2026-09-21.sql
--        docker exec -i supabase_db_ZenWard psql -U postgres -d postgres -f - < supabase/migrations/20260921110000_production_privilege_baseline_hardening.sql
--        scripts/verify-db-privileges.sh local        # expect 0 violations
--        docker exec supabase_db_ZenWard psql -U postgres -d postgres -c "drop function if exists public.rls_auto_enable()"
--   2. Reference for restoring the previous grants if the hardening ever had to be reverted (review before use:
--      it re-opens anon/authenticated/service_role privileges that the contract deliberately removed).
-- It also creates a stand-in public.rls_auto_enable() event-trigger function (installed by the Supabase
-- platform in production) so the migration's platform-helper branch is exercised locally.
-- emulate PRODUCTION ACL starting state (from read-only inventory 2026-09-21)
alter default privileges for role postgres grant execute on functions to public;
alter default privileges for role postgres in schema extensions revoke execute on functions from public;   -- production has no schema-scoped default row for extensions
alter default privileges for role postgres in schema public grant select,insert,update,delete on tables to anon, authenticated;
alter default privileges for role postgres in schema public grant all on tables to service_role;
alter default privileges for role postgres in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public grant execute on functions to anon, authenticated, service_role;
revoke all on sequence public."public_intake_rate_limit_events_id_seq" from public, anon, authenticated, service_role;
grant SELECT,UPDATE,USAGE on sequence public."public_intake_rate_limit_events_id_seq" to anon;
grant SELECT,UPDATE,USAGE on sequence public."public_intake_rate_limit_events_id_seq" to service_role;
grant SELECT,UPDATE,USAGE on sequence public."public_intake_rate_limit_events_id_seq" to authenticated;
revoke all on table public."audit_events" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."audit_events" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."audit_events" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."audit_events" to authenticated;
revoke all on table public."driver_invites" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."driver_invites" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."driver_invites" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."driver_invites" to authenticated;
revoke all on table public."driver_location_updates" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."driver_location_updates" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."driver_location_updates" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."driver_location_updates" to authenticated;
revoke all on table public."drivers" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."drivers" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."drivers" to service_role;
grant DELETE,SELECT on table public."drivers" to authenticated;
revoke all on table public."facilities" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."facilities" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."facilities" to service_role;
grant DELETE,INSERT,SELECT on table public."facilities" to authenticated;
revoke all on table public."memberships" from public, anon, authenticated, service_role;
grant SELECT on table public."memberships" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."memberships" to service_role;
grant SELECT on table public."memberships" to authenticated;
revoke all on table public."notification_events" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."notification_events" to service_role;
revoke all on table public."organization_notification_settings" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."organization_notification_settings" to service_role;
revoke all on table public."organization_service_offerings" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."organization_service_offerings" to service_role;
revoke all on table public."organizations" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT on table public."organizations" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."organizations" to service_role;
grant DELETE,INSERT,SELECT on table public."organizations" to authenticated;
revoke all on table public."passengers" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."passengers" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."passengers" to service_role;
grant DELETE,INSERT,SELECT on table public."passengers" to authenticated;
revoke all on table public."platform_admin_grants" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."platform_admin_grants" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."platform_admin_grants" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."platform_admin_grants" to authenticated;
revoke all on table public."public_intake_rate_limit_events" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."public_intake_rate_limit_events" to service_role;
revoke all on table public."recurring_arrangements" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."recurring_arrangements" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."recurring_arrangements" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."recurring_arrangements" to authenticated;
revoke all on table public."recurring_occurrence_exceptions" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."recurring_occurrence_exceptions" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."recurring_occurrence_exceptions" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."recurring_occurrence_exceptions" to authenticated;
revoke all on table public."request_events" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."request_events" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."request_events" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."request_events" to authenticated;
revoke all on table public."request_intake_integrations" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."request_intake_integrations" to service_role;
revoke all on table public."staff_invites" from public, anon, authenticated, service_role;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."staff_invites" to service_role;
revoke all on table public."transportation_requests" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."transportation_requests" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."transportation_requests" to service_role;
grant DELETE,SELECT on table public."transportation_requests" to authenticated;
revoke all on table public."trip_assignments" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_assignments" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."trip_assignments" to service_role;
grant DELETE,SELECT on table public."trip_assignments" to authenticated;
revoke all on table public."trip_events" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_events" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."trip_events" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_events" to authenticated;
revoke all on table public."trip_exceptions" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_exceptions" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."trip_exceptions" to service_role;
grant DELETE,SELECT on table public."trip_exceptions" to authenticated;
revoke all on table public."trip_notes" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_notes" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."trip_notes" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trip_notes" to authenticated;
revoke all on table public."trips" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."trips" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."trips" to service_role;
grant DELETE,SELECT on table public."trips" to authenticated;
revoke all on table public."user_profiles" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."user_profiles" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."user_profiles" to service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."user_profiles" to authenticated;
revoke all on table public."vehicles" from public, anon, authenticated, service_role;
grant DELETE,INSERT,SELECT,UPDATE on table public."vehicles" to anon;
grant DELETE,INSERT,MAINTAIN,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE on table public."vehicles" to service_role;
grant DELETE,INSERT,SELECT on table public."vehicles" to authenticated;
grant UPDATE ("display_name") on table public."drivers" to authenticated;
grant UPDATE ("phone") on table public."drivers" to authenticated;
grant UPDATE ("status") on table public."drivers" to authenticated;
grant UPDATE ("address_line1") on table public."facilities" to authenticated;
grant UPDATE ("address_line2") on table public."facilities" to authenticated;
grant UPDATE ("city") on table public."facilities" to authenticated;
grant UPDATE ("name") on table public."facilities" to authenticated;
grant UPDATE ("postal_code") on table public."facilities" to authenticated;
grant UPDATE ("state") on table public."facilities" to authenticated;
grant UPDATE ("status") on table public."facilities" to authenticated;
grant UPDATE ("assistance_notes") on table public."passengers" to authenticated;
grant UPDATE ("display_name") on table public."passengers" to authenticated;
grant UPDATE ("phone") on table public."passengers" to authenticated;
grant UPDATE ("status") on table public."passengers" to authenticated;
grant UPDATE ("additional_notes") on table public."transportation_requests" to authenticated;
grant UPDATE ("assistance_notes") on table public."transportation_requests" to authenticated;
grant UPDATE ("destination_description") on table public."transportation_requests" to authenticated;
grant UPDATE ("pickup_description") on table public."transportation_requests" to authenticated;
grant UPDATE ("preferred_date") on table public."transportation_requests" to authenticated;
grant UPDATE ("preferred_time") on table public."transportation_requests" to authenticated;
grant UPDATE ("requester_email") on table public."transportation_requests" to authenticated;
grant UPDATE ("requester_name") on table public."transportation_requests" to authenticated;
grant UPDATE ("requester_phone") on table public."transportation_requests" to authenticated;
grant UPDATE ("requester_relationship") on table public."transportation_requests" to authenticated;
grant UPDATE ("return_trip_needed") on table public."transportation_requests" to authenticated;
grant UPDATE ("source") on table public."transportation_requests" to authenticated;
grant UPDATE ("appointment_at") on table public."trips" to authenticated;
grant UPDATE ("assistance_notes") on table public."trips" to authenticated;
grant UPDATE ("destination_description") on table public."trips" to authenticated;
grant UPDATE ("destination_facility_id") on table public."trips" to authenticated;
grant UPDATE ("instructions") on table public."trips" to authenticated;
grant UPDATE ("pickup_description") on table public."trips" to authenticated;
grant UPDATE ("pickup_facility_id") on table public."trips" to authenticated;
grant UPDATE ("scheduled_pickup_at") on table public."trips" to authenticated;
grant UPDATE ("label") on table public."vehicles" to authenticated;
grant UPDATE ("status") on table public."vehicles" to authenticated;
create or replace function public.rls_auto_enable() returns event_trigger language plpgsql security definer set search_path = pg_catalog as $$ begin null; end $$;
revoke all on function _driver_execute_trip_transition(uuid,text,text,text,text,boolean) from public, anon, authenticated, service_role;
grant execute on function _driver_execute_trip_transition(uuid,text,text,text,text,boolean) to anon;
grant execute on function _driver_execute_trip_transition(uuid,text,text,text,text,boolean) to service_role;
grant execute on function _driver_execute_trip_transition(uuid,text,text,text,text,boolean) to authenticated;
revoke all on function _enqueue_notification_event(uuid,text,text,uuid) from public, anon, authenticated, service_role;
grant execute on function _enqueue_notification_event(uuid,text,text,uuid) to service_role;
revoke all on function _generate_intake_external_id() from public, anon, authenticated, service_role;
grant execute on function _generate_intake_external_id() to service_role;
revoke all on function _generate_staff_invite_token() from public, anon, authenticated, service_role;
grant execute on function _generate_staff_invite_token() to service_role;
revoke all on function _is_canonical_days_of_week(smallint[]) from public, anon, authenticated, service_role;
grant execute on function _is_canonical_days_of_week(smallint[]) to anon;
grant execute on function _is_canonical_days_of_week(smallint[]) to service_role;
grant execute on function _is_canonical_days_of_week(smallint[]) to authenticated;
revoke all on function _is_valid_trip_transition(text,text) from public, anon, authenticated, service_role;
grant execute on function _is_valid_trip_transition(text,text) to anon;
grant execute on function _is_valid_trip_transition(text,text) to service_role;
grant execute on function _is_valid_trip_transition(text,text) to authenticated;
revoke all on function _lock_driver_active_assignment(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function _lock_driver_active_assignment(uuid,uuid) to anon;
grant execute on function _lock_driver_active_assignment(uuid,uuid) to service_role;
grant execute on function _lock_driver_active_assignment(uuid,uuid) to authenticated;
revoke all on function _lock_org_admins(uuid) from public, anon, authenticated, service_role;
grant execute on function _lock_org_admins(uuid) to service_role;
revoke all on function _normalize_website_origin(text) from public, anon, authenticated, service_role;
grant execute on function _normalize_website_origin(text) to service_role;
revoke all on function _notification_default_roles(text) from public, anon, authenticated, service_role;
grant execute on function _notification_default_roles(text) to service_role;
revoke all on function _organization_local_to_utc(date,time without time zone,text) from public, anon, authenticated, service_role;
grant execute on function _organization_local_to_utc(date,time without time zone,text) to anon;
grant execute on function _organization_local_to_utc(date,time without time zone,text) to service_role;
grant execute on function _organization_local_to_utc(date,time without time zone,text) to authenticated;
revoke all on function _require_platform_admin() from public, anon, authenticated, service_role;
grant execute on function _require_platform_admin() to service_role;
revoke all on function _staff_invite_token_hash(text) from public, anon, authenticated, service_role;
grant execute on function _staff_invite_token_hash(text) to service_role;
revoke all on function accept_staff_invite(text) from public, anon, authenticated, service_role;
grant execute on function accept_staff_invite(text) to anon;
grant execute on function accept_staff_invite(text) to service_role;
grant execute on function accept_staff_invite(text) to authenticated;
revoke all on function assign_trip(uuid,uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function assign_trip(uuid,uuid,uuid) to anon;
grant execute on function assign_trip(uuid,uuid,uuid) to service_role;
grant execute on function assign_trip(uuid,uuid,uuid) to authenticated;
revoke all on function cancel_staff_invite(uuid) from public, anon, authenticated, service_role;
grant execute on function cancel_staff_invite(uuid) to anon;
grant execute on function cancel_staff_invite(uuid) to service_role;
grant execute on function cancel_staff_invite(uuid) to authenticated;
revoke all on function cancel_transportation_request(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function cancel_transportation_request(uuid,uuid) to anon;
grant execute on function cancel_transportation_request(uuid,uuid) to service_role;
grant execute on function cancel_transportation_request(uuid,uuid) to authenticated;
revoke all on function cancel_trip(uuid,text) from public, anon, authenticated, service_role;
grant execute on function cancel_trip(uuid,text) to anon;
grant execute on function cancel_trip(uuid,text) to service_role;
grant execute on function cancel_trip(uuid,text) to authenticated;
revoke all on function change_membership_role(uuid,text) from public, anon, authenticated, service_role;
grant execute on function change_membership_role(uuid,text) to anon;
grant execute on function change_membership_role(uuid,text) to service_role;
grant execute on function change_membership_role(uuid,text) to authenticated;
revoke all on function check_and_record_public_intake_rate_limit(text,text) from public, anon, authenticated, service_role;
grant execute on function check_and_record_public_intake_rate_limit(text,text) to service_role;
revoke all on function claim_notification_dispatch(uuid) from public, anon, authenticated, service_role;
grant execute on function claim_notification_dispatch(uuid) to service_role;
revoke all on function complete_notification_dispatch(uuid,integer,integer,text) from public, anon, authenticated, service_role;
grant execute on function complete_notification_dispatch(uuid,integer,integer,text) to service_role;
revoke all on function complete_pending_signup() from public, anon, authenticated, service_role;
grant execute on function complete_pending_signup() to anon;
grant execute on function complete_pending_signup() to service_role;
grant execute on function complete_pending_signup() to authenticated;
revoke all on function complete_pending_signup_manual(text,text) from public, anon, authenticated, service_role;
grant execute on function complete_pending_signup_manual(text,text) to anon;
grant execute on function complete_pending_signup_manual(text,text) to service_role;
grant execute on function complete_pending_signup_manual(text,text) to authenticated;
revoke all on function create_driver_invite(uuid,text,text,text) from public, anon, authenticated, service_role;
grant execute on function create_driver_invite(uuid,text,text,text) to anon;
grant execute on function create_driver_invite(uuid,text,text,text) to service_role;
grant execute on function create_driver_invite(uuid,text,text,text) to authenticated;
revoke all on function create_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) from public, anon, authenticated, service_role;
grant execute on function create_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to anon;
grant execute on function create_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to service_role;
grant execute on function create_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to authenticated;
revoke all on function create_request_intake_integration(uuid,text) from public, anon, authenticated, service_role;
grant execute on function create_request_intake_integration(uuid,text) to anon;
grant execute on function create_request_intake_integration(uuid,text) to service_role;
grant execute on function create_request_intake_integration(uuid,text) to authenticated;
revoke all on function create_staff_invite(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function create_staff_invite(uuid,text,text) to anon;
grant execute on function create_staff_invite(uuid,text,text) to service_role;
grant execute on function create_staff_invite(uuid,text,text) to authenticated;
revoke all on function create_trip(uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,uuid,uuid,text,text,uuid) from public, anon, authenticated, service_role;
grant execute on function create_trip(uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,uuid,uuid,text,text,uuid) to anon;
grant execute on function create_trip(uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,uuid,uuid,text,text,uuid) to service_role;
grant execute on function create_trip(uuid,uuid,text,text,timestamp with time zone,timestamp with time zone,uuid,uuid,text,text,uuid) to authenticated;
revoke all on function create_trip_for_recurring_occurrence(uuid,uuid,date) from public, anon, authenticated, service_role;
grant execute on function create_trip_for_recurring_occurrence(uuid,uuid,date) to anon;
grant execute on function create_trip_for_recurring_occurrence(uuid,uuid,date) to service_role;
grant execute on function create_trip_for_recurring_occurrence(uuid,uuid,date) to authenticated;
revoke all on function current_driver_id(uuid) from public, anon, authenticated, service_role;
grant execute on function current_driver_id(uuid) to anon;
grant execute on function current_driver_id(uuid) to service_role;
grant execute on function current_driver_id(uuid) to authenticated;
revoke all on function decline_transportation_request(uuid,uuid,text) from public, anon, authenticated, service_role;
grant execute on function decline_transportation_request(uuid,uuid,text) to anon;
grant execute on function decline_transportation_request(uuid,uuid,text) to service_role;
grant execute on function decline_transportation_request(uuid,uuid,text) to authenticated;
revoke all on function driver_arrive_at_destination(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_arrive_at_destination(uuid,text) to anon;
grant execute on function driver_arrive_at_destination(uuid,text) to service_role;
grant execute on function driver_arrive_at_destination(uuid,text) to authenticated;
revoke all on function driver_arrive_at_pickup(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_arrive_at_pickup(uuid,text) to anon;
grant execute on function driver_arrive_at_pickup(uuid,text) to service_role;
grant execute on function driver_arrive_at_pickup(uuid,text) to authenticated;
revoke all on function driver_complete_trip(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_complete_trip(uuid,text) to anon;
grant execute on function driver_complete_trip(uuid,text) to service_role;
grant execute on function driver_complete_trip(uuid,text) to authenticated;
revoke all on function driver_get_profile(uuid) from public, anon, authenticated, service_role;
grant execute on function driver_get_profile(uuid) to anon;
grant execute on function driver_get_profile(uuid) to service_role;
grant execute on function driver_get_profile(uuid) to authenticated;
revoke all on function driver_get_trip_detail(uuid) from public, anon, authenticated, service_role;
grant execute on function driver_get_trip_detail(uuid) to anon;
grant execute on function driver_get_trip_detail(uuid) to service_role;
grant execute on function driver_get_trip_detail(uuid) to authenticated;
revoke all on function driver_list_active_trips(uuid) from public, anon, authenticated, service_role;
grant execute on function driver_list_active_trips(uuid) to anon;
grant execute on function driver_list_active_trips(uuid) to service_role;
grant execute on function driver_list_active_trips(uuid) to authenticated;
revoke all on function driver_list_trip_history(uuid,timestamp with time zone,timestamp with time zone) from public, anon, authenticated, service_role;
grant execute on function driver_list_trip_history(uuid,timestamp with time zone,timestamp with time zone) to anon;
grant execute on function driver_list_trip_history(uuid,timestamp with time zone,timestamp with time zone) to service_role;
grant execute on function driver_list_trip_history(uuid,timestamp with time zone,timestamp with time zone) to authenticated;
revoke all on function driver_mark_passenger_onboard(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_mark_passenger_onboard(uuid,text) to anon;
grant execute on function driver_mark_passenger_onboard(uuid,text) to service_role;
grant execute on function driver_mark_passenger_onboard(uuid,text) to authenticated;
revoke all on function driver_record_location(uuid,double precision,double precision,double precision) from public, anon, authenticated, service_role;
grant execute on function driver_record_location(uuid,double precision,double precision,double precision) to anon;
grant execute on function driver_record_location(uuid,double precision,double precision,double precision) to service_role;
grant execute on function driver_record_location(uuid,double precision,double precision,double precision) to authenticated;
revoke all on function driver_start_to_destination(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_start_to_destination(uuid,text) to anon;
grant execute on function driver_start_to_destination(uuid,text) to service_role;
grant execute on function driver_start_to_destination(uuid,text) to authenticated;
revoke all on function driver_start_to_pickup(uuid,text) from public, anon, authenticated, service_role;
grant execute on function driver_start_to_pickup(uuid,text) to anon;
grant execute on function driver_start_to_pickup(uuid,text) to service_role;
grant execute on function driver_start_to_pickup(uuid,text) to authenticated;
revoke all on function edit_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) from public, anon, authenticated, service_role;
grant execute on function edit_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to anon;
grant execute on function edit_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to service_role;
grant execute on function edit_recurring_arrangement(uuid,uuid,text,text,time without time zone,smallint[],date,date) to authenticated;
revoke all on function end_recurring_arrangement(uuid,uuid,text) from public, anon, authenticated, service_role;
grant execute on function end_recurring_arrangement(uuid,uuid,text) to anon;
grant execute on function end_recurring_arrangement(uuid,uuid,text) to service_role;
grant execute on function end_recurring_arrangement(uuid,uuid,text) to authenticated;
revoke all on function get_driver_invite_preview(uuid) from public, anon, authenticated, service_role;
grant execute on function get_driver_invite_preview(uuid) to anon;
grant execute on function get_driver_invite_preview(uuid) to service_role;
grant execute on function get_driver_invite_preview(uuid) to authenticated;
revoke all on function get_notification_settings(uuid) from public, anon, authenticated, service_role;
grant execute on function get_notification_settings(uuid) to anon;
grant execute on function get_notification_settings(uuid) to service_role;
grant execute on function get_notification_settings(uuid) to authenticated;
revoke all on function get_organization_service_offerings(uuid) from public, anon, authenticated, service_role;
grant execute on function get_organization_service_offerings(uuid) to anon;
grant execute on function get_organization_service_offerings(uuid) to service_role;
grant execute on function get_organization_service_offerings(uuid) to authenticated;
revoke all on function get_staff_invite_preview(text) from public, anon, authenticated, service_role;
grant execute on function get_staff_invite_preview(text) to anon;
grant execute on function get_staff_invite_preview(text) to service_role;
grant execute on function get_staff_invite_preview(text) to authenticated;
revoke all on function has_org_role(uuid,text[]) from public, anon, authenticated, service_role;
grant execute on function has_org_role(uuid,text[]) to anon;
grant execute on function has_org_role(uuid,text[]) to service_role;
grant execute on function has_org_role(uuid,text[]) to authenticated;
revoke all on function is_driver_assigned_to_trip(uuid) from public, anon, authenticated, service_role;
grant execute on function is_driver_assigned_to_trip(uuid) to anon;
grant execute on function is_driver_assigned_to_trip(uuid) to service_role;
grant execute on function is_driver_assigned_to_trip(uuid) to authenticated;
revoke all on function is_org_member(uuid) from public, anon, authenticated, service_role;
grant execute on function is_org_member(uuid) to anon;
grant execute on function is_org_member(uuid) to service_role;
grant execute on function is_org_member(uuid) to authenticated;
revoke all on function is_platform_admin() from public, anon, authenticated, service_role;
grant execute on function is_platform_admin() to anon;
grant execute on function is_platform_admin() to service_role;
grant execute on function is_platform_admin() to authenticated;
revoke all on function is_valid_iana_timezone(text) from public, anon, authenticated, service_role;
grant execute on function is_valid_iana_timezone(text) to anon;
grant execute on function is_valid_iana_timezone(text) to service_role;
grant execute on function is_valid_iana_timezone(text) to authenticated;
revoke all on function link_request_passenger(uuid,uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function link_request_passenger(uuid,uuid,uuid) to anon;
grant execute on function link_request_passenger(uuid,uuid,uuid) to service_role;
grant execute on function link_request_passenger(uuid,uuid,uuid) to authenticated;
revoke all on function link_self_as_driver(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function link_self_as_driver(uuid,text,text) to anon;
grant execute on function link_self_as_driver(uuid,text,text) to service_role;
grant execute on function link_self_as_driver(uuid,text,text) to authenticated;
revoke all on function list_activity_events(uuid,integer,timestamp with time zone,uuid) from public, anon, authenticated, service_role;
grant execute on function list_activity_events(uuid,integer,timestamp with time zone,uuid) to anon;
grant execute on function list_activity_events(uuid,integer,timestamp with time zone,uuid) to service_role;
grant execute on function list_activity_events(uuid,integer,timestamp with time zone,uuid) to authenticated;
revoke all on function list_notification_history(uuid,integer) from public, anon, authenticated, service_role;
grant execute on function list_notification_history(uuid,integer) to anon;
grant execute on function list_notification_history(uuid,integer) to service_role;
grant execute on function list_notification_history(uuid,integer) to authenticated;
revoke all on function list_request_intake_integrations(uuid) from public, anon, authenticated, service_role;
grant execute on function list_request_intake_integrations(uuid) to anon;
grant execute on function list_request_intake_integrations(uuid) to service_role;
grant execute on function list_request_intake_integrations(uuid) to authenticated;
revoke all on function list_staff_invites(uuid) from public, anon, authenticated, service_role;
grant execute on function list_staff_invites(uuid) to anon;
grant execute on function list_staff_invites(uuid) to service_role;
grant execute on function list_staff_invites(uuid) to authenticated;
revoke all on function list_team_members(uuid) from public, anon, authenticated, service_role;
grant execute on function list_team_members(uuid) to anon;
grant execute on function list_team_members(uuid) to service_role;
grant execute on function list_team_members(uuid) to authenticated;
revoke all on function log_transportation_request(uuid,text,text,text,text,text,text,text,text,uuid,date,time without time zone,text,text) from public, anon, authenticated, service_role;
grant execute on function log_transportation_request(uuid,text,text,text,text,text,text,text,text,uuid,date,time without time zone,text,text) to anon;
grant execute on function log_transportation_request(uuid,text,text,text,text,text,text,text,text,uuid,date,time without time zone,text,text) to service_role;
grant execute on function log_transportation_request(uuid,text,text,text,text,text,text,text,text,uuid,date,time without time zone,text,text) to authenticated;
revoke all on function pause_recurring_arrangement(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function pause_recurring_arrangement(uuid,uuid) to anon;
grant execute on function pause_recurring_arrangement(uuid,uuid) to service_role;
grant execute on function pause_recurring_arrangement(uuid,uuid) to authenticated;
revoke all on function platform_get_organization(uuid) from public, anon, authenticated, service_role;
grant execute on function platform_get_organization(uuid) to service_role;
grant execute on function platform_get_organization(uuid) to authenticated;
revoke all on function platform_get_overview() from public, anon, authenticated, service_role;
grant execute on function platform_get_overview() to service_role;
grant execute on function platform_get_overview() to authenticated;
revoke all on function platform_list_activity(integer,timestamp with time zone,uuid) from public, anon, authenticated, service_role;
grant execute on function platform_list_activity(integer,timestamp with time zone,uuid) to service_role;
grant execute on function platform_list_activity(integer,timestamp with time zone,uuid) to authenticated;
revoke all on function platform_list_notification_attention(integer) from public, anon, authenticated, service_role;
grant execute on function platform_list_notification_attention(integer) to service_role;
grant execute on function platform_list_notification_attention(integer) to authenticated;
revoke all on function platform_list_organization_integrations(uuid) from public, anon, authenticated, service_role;
grant execute on function platform_list_organization_integrations(uuid) to service_role;
grant execute on function platform_list_organization_integrations(uuid) to authenticated;
revoke all on function platform_list_organizations(text,text,integer,integer) from public, anon, authenticated, service_role;
grant execute on function platform_list_organizations(text,text,integer,integer) to service_role;
grant execute on function platform_list_organizations(text,text,integer,integer) to authenticated;
revoke all on function prevent_organization_id_change() from public, anon, authenticated, service_role;
grant execute on function prevent_organization_id_change() to anon;
grant execute on function prevent_organization_id_change() to service_role;
grant execute on function prevent_organization_id_change() to authenticated;
revoke all on function reassign_trip(uuid,uuid,uuid,text,uuid) from public, anon, authenticated, service_role;
grant execute on function reassign_trip(uuid,uuid,uuid,text,uuid) to anon;
grant execute on function reassign_trip(uuid,uuid,uuid,text,uuid) to service_role;
grant execute on function reassign_trip(uuid,uuid,uuid,text,uuid) to authenticated;
revoke all on function record_no_show(uuid,text) from public, anon, authenticated, service_role;
grant execute on function record_no_show(uuid,text) to anon;
grant execute on function record_no_show(uuid,text) to service_role;
grant execute on function record_no_show(uuid,text) to authenticated;
revoke all on function redeem_driver_invite(uuid) from public, anon, authenticated, service_role;
grant execute on function redeem_driver_invite(uuid) to anon;
grant execute on function redeem_driver_invite(uuid) to service_role;
grant execute on function redeem_driver_invite(uuid) to authenticated;
revoke all on function report_trip_exception(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function report_trip_exception(uuid,text,text) to anon;
grant execute on function report_trip_exception(uuid,text,text) to service_role;
grant execute on function report_trip_exception(uuid,text,text) to authenticated;
revoke all on function resend_staff_invite(uuid) from public, anon, authenticated, service_role;
grant execute on function resend_staff_invite(uuid) to anon;
grant execute on function resend_staff_invite(uuid) to service_role;
grant execute on function resend_staff_invite(uuid) to authenticated;
revoke all on function resolve_trip_exception(uuid,text) from public, anon, authenticated, service_role;
grant execute on function resolve_trip_exception(uuid,text) to anon;
grant execute on function resolve_trip_exception(uuid,text) to service_role;
grant execute on function resolve_trip_exception(uuid,text) to authenticated;
revoke all on function resume_recurring_arrangement(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function resume_recurring_arrangement(uuid,uuid) to anon;
grant execute on function resume_recurring_arrangement(uuid,uuid) to service_role;
grant execute on function resume_recurring_arrangement(uuid,uuid) to authenticated;
revoke all on function revoke_driver_invite(uuid) from public, anon, authenticated, service_role;
grant execute on function revoke_driver_invite(uuid) to anon;
grant execute on function revoke_driver_invite(uuid) to service_role;
grant execute on function revoke_driver_invite(uuid) to authenticated;
revoke all on function rls_auto_enable() from public, anon, authenticated, service_role;
grant execute on function rls_auto_enable() to anon;
grant execute on function rls_auto_enable() to public;
grant execute on function rls_auto_enable() to service_role;
grant execute on function rls_auto_enable() to authenticated;
revoke all on function set_membership_status(uuid,boolean) from public, anon, authenticated, service_role;
grant execute on function set_membership_status(uuid,boolean) to anon;
grant execute on function set_membership_status(uuid,boolean) to service_role;
grant execute on function set_membership_status(uuid,boolean) to authenticated;
revoke all on function set_notification_settings(uuid,text,text[]) from public, anon, authenticated, service_role;
grant execute on function set_notification_settings(uuid,text,text[]) to anon;
grant execute on function set_notification_settings(uuid,text,text[]) to service_role;
grant execute on function set_notification_settings(uuid,text,text[]) to authenticated;
revoke all on function set_organization_service_offerings(uuid,text[]) from public, anon, authenticated, service_role;
grant execute on function set_organization_service_offerings(uuid,text[]) to anon;
grant execute on function set_organization_service_offerings(uuid,text[]) to service_role;
grant execute on function set_organization_service_offerings(uuid,text[]) to authenticated;
revoke all on function set_platform_organization_status(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function set_platform_organization_status(uuid,text,text) to service_role;
grant execute on function set_platform_organization_status(uuid,text,text) to authenticated;
revoke all on function set_request_intake_integration_active(uuid,boolean) from public, anon, authenticated, service_role;
grant execute on function set_request_intake_integration_active(uuid,boolean) to anon;
grant execute on function set_request_intake_integration_active(uuid,boolean) to service_role;
grant execute on function set_request_intake_integration_active(uuid,boolean) to authenticated;
revoke all on function set_updated_at() from public, anon, authenticated, service_role;
grant execute on function set_updated_at() to anon;
grant execute on function set_updated_at() to service_role;
grant execute on function set_updated_at() to authenticated;
revoke all on function signup_create_organization(text,text,text,text) from public, anon, authenticated, service_role;
grant execute on function signup_create_organization(text,text,text,text) to anon;
grant execute on function signup_create_organization(text,text,text,text) to service_role;
revoke all on function skip_recurring_occurrence(uuid,uuid,date,text) from public, anon, authenticated, service_role;
grant execute on function skip_recurring_occurrence(uuid,uuid,date,text) to anon;
grant execute on function skip_recurring_occurrence(uuid,uuid,date,text) to service_role;
grant execute on function skip_recurring_occurrence(uuid,uuid,date,text) to authenticated;
revoke all on function submit_public_transportation_request(text,text,text,text,text,text,text,text,text,date,time without time zone,text,text,text,text,text[],date,date,time without time zone,boolean,text) from public, anon, authenticated, service_role;
grant execute on function submit_public_transportation_request(text,text,text,text,text,text,text,text,text,date,time without time zone,text,text,text,text,text[],date,date,time without time zone,boolean,text) to service_role;
revoke all on function unskip_recurring_occurrence(uuid,uuid,date) from public, anon, authenticated, service_role;
grant execute on function unskip_recurring_occurrence(uuid,uuid,date) to anon;
grant execute on function unskip_recurring_occurrence(uuid,uuid,date) to service_role;
grant execute on function unskip_recurring_occurrence(uuid,uuid,date) to authenticated;
revoke all on function update_organization_operating_schedule(uuid,smallint[],time without time zone,time without time zone) from public, anon, authenticated, service_role;
grant execute on function update_organization_operating_schedule(uuid,smallint[],time without time zone,time without time zone) to anon;
grant execute on function update_organization_operating_schedule(uuid,smallint[],time without time zone,time without time zone) to service_role;
grant execute on function update_organization_operating_schedule(uuid,smallint[],time without time zone,time without time zone) to authenticated;
revoke all on function update_organization_settings(uuid,jsonb) from public, anon, authenticated, service_role;
grant execute on function update_organization_settings(uuid,jsonb) to anon;
grant execute on function update_organization_settings(uuid,jsonb) to service_role;
grant execute on function update_organization_settings(uuid,jsonb) to authenticated;
revoke all on function update_request_intake_integration_origin(uuid,text) from public, anon, authenticated, service_role;
grant execute on function update_request_intake_integration_origin(uuid,text) to anon;
grant execute on function update_request_intake_integration_origin(uuid,text) to service_role;
grant execute on function update_request_intake_integration_origin(uuid,text) to authenticated;
